image: python:3.7.3

before_script:
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py --silent -o get-poetry.py
  - python get-poetry.py -y --version 1.0.0
  - source $HOME/.poetry/env
  - poetry config virtualenvs.create false
  - poetry install --no-root
  - export PYTHONPATH="$PWD/src"

code_analysis:
  stage: test
  script:
    - ./pylint.sh
    - ./check-crlf.sh
